Explicitly import `tornado.locks`
finos/perspective pull request #1227
Opened 2020-10-19 17:57 UTC by sc1f

`tornado.locks` is not included in the `__init__.py` of older Tornado versions, and this causes an issue when hosting Perspective servers as we don't explicitly import `tornado.locks`. This patch makes the import explicit and pins a version of Tornado for our Python 2 builds.

2020-10-19 18:01 UTC, timkpaine requested changes

2020-10-19 18:01 UTC, timkpaine commented on python/perspective/setup.py
> +    "tornado>=4.5.3",
needs to match pyproject.toml

2020-10-19 18:01 UTC, timkpaine commented on python/perspective/setup.py
> +    requires += ["tornado==4.5.3", "backports.shutil-which"]
don't hard equals here

2020-10-19 18:01 UTC, timkpaine commented on python/perspective/setup.py
> +    "tornado>=4.5.3",
also keep alphabetical

2020-10-20 14:07 UTC, timkpaine approved these changes

2020-10-23 06:00 UTC, texodus commented
Thanks for the PR!

2020-10-23 06:01 UTC, merged