Restrict `viewer.load()` to only accept `Table()`
finos/perspective pull request #1231
Opened 2020-10-23 06:00 UTC by texodus

2020-10-28 14:55 UTC, sc1f requested changes
`PerspectiveWidget` is currently broken on this branch - verified locally and through code review.

Intuitively, we should also make sure that `PerspectiveWidget` follows this API change - i.e. it should only `__init__` or `load` with a table and not a dataset.

2020-10-28 14:55 UTC, sc1f commented on packages/perspective-jupyterlab/src/ts/view.ts
> +                    kernel_view.to_arrow().then((arrow: ArrayBuffer) => {
This breaks - there is no `on_update` callback so when the table on the kernel updates, it will not reflect in the widget.

2020-10-28 14:55 UTC, sc1f commented on packages/perspective-jupyterlab/test/js/unit/view.spec.js
> +                // expect(load_args[1]).toEqual(options);
We can use get_index() or get_limit() here to make sure it's been applied properly.

2020-11-05 17:08 UTC, sc1f approved these changes
Looks good! This should be merged before #1240 - there will be some conflicts on that PR (in the jupyterlab plugin and tests) that I will fix after this branch is merged.

2020-12-22 09:33 UTC, merged

2021-01-18 21:11 UTC, timkpaine commented on packages/perspective-jupyterlab/src/ts/psp_widget.ts
> +        this.viewer.table.update(data);
`TypeError: this.viewer.table is undefined`

2021-01-18 21:12 UTC, timkpaine commented on packages/perspective-jupyterlab/src/ts/psp_widget.ts
> +        this.viewer.table.update(data);
this introduces a bug as `table` isn't guaranteed to exist on the viewer. I don't think this was checked?