Reimplement pandas deconstruction
finos/perspective pull request #1238
Opened 2020-10-28 23:16 UTC by timkpaine

Pivoted Pandas dataframe deconstruction is fundamentally broken in our current state, as exhibited by a few issues (#1122, #1123, etc). This PR rectifies that problem by better deconstructing pivoted data frames.

Also changed:
- Certain pivoted data frames had ' ' columns for visual style, this is changed to 'value' to be more sensible.
- Date/Datetime arguments to filter are converted to their string representation (unrelated to pandas)

Notebooks and test cases updated/added.

2020-10-29 19:39 UTC, sc1f requested changes
Can we split the commits where we run `black` into a separate PR? There's too much reformatting noise to discern the real changes as part of this PR.

2020-10-29 19:42 UTC, timkpaine commented on python/perspective/perspective/tests/widget/test_widget_pandas.py
> +    def test_pivottable_values_index(self):
these are the only changes, addition of 2 tests

2020-10-30 02:04 UTC, sc1f approved these changes
Checked out locally - changes, examples and reformatting look good. @texodus we should probably merge this first and rebase, or manually split it into two PRs just so that other PRs aren't mired in merge issues.

Thanks for fixing the datetime issue! It is only a fix for the Python widget side - for a more comprehensive fix we need to target the date parser in JS/C++ and make it more user-friendly.

2020-12-22 05:06 UTC, texodus commented
Looks good!  Thanks for the PR!

2020-12-22 05:06 UTC, merged