Fix timezone tests to take DST into account
finos/perspective pull request #1349
Opened 2021-03-15 21:05 UTC by sc1f

In our suite of timezone tests, we set the timezone manually and assert that `getTimezoneOffset` is 300 (for EST). However, during Daylight Savings time (which started on Sunday, March 14th) the timezone offset is 240, and our tests did not take that into account. This PR fixes the issue and now should work for both DST and non-DST times.

2021-03-16 03:13 UTC, timkpaine requested changes

2021-03-16 03:13 UTC, timkpaine commented on yarn.lock
> +"@finos/perspective-viewer-d3fc@^0.5.1":
probably can omit these yarn.lock changes

2021-03-16 16:02 UTC, sc1f commented on yarn.lock
> +"@finos/perspective-viewer-d3fc@^0.5.1":
fixed

2021-03-16 16:28 UTC, timkpaine approved these changes

2021-03-16 16:29 UTC, timkpaine commented
@sc1f looks like they mightve moved boost again on windows 🤦

2021-03-16 16:48 UTC, sc1f commented
@timkpaine PR build successful though, which is strange - let me bump the windows job

2021-03-16 16:50 UTC, sc1f commented
@timkpaine https://github.com/actions/virtual-environments/issues/2667 welp - I will make a PR fixing this

2021-03-16 17:00 UTC, texodus commented
Honest question - why do we depend on system boost for Windows instead of building the version we want as we do [for wasm](https://github.com/finos/perspective/blob/master/scripts/install_tools.js)?

2021-03-16 17:03 UTC, sc1f commented
@texodus we don't have a docker image for windows; I think we may need the built boost and not just the headers, but I will check when I do the fix.

2021-03-16 17:03 UTC, timkpaine commented
@texodus if you want to make that script cross-platform...

2021-03-17 02:16 UTC, texodus commented
@timkpaine I made this change on the wasm workflow because I measured it was faster overall to build boost from source, as opposed to loading the Docker image, if you include cumulative build time saved from skipping the container.  Ideally this will use Azure's cache to build `boost` once per week or so, but I've yet to get this part to work - regardless the total boost time is ~3min [source](https://dev.azure.com/finosfoundation/perspective/_build/results?buildId=2194&view=logs&j=430750e5-873f-5cdb-f7d1-334fffa69fc8&t=e9a709ee-98dc-5d78-ab76-09541ac9f110) which is longer than downloading the container by ~1min, but significantly faster to build perspective overall for wasm outside of the container.  This won't translate 1:1 with Python but it won't be off by more than a handful of minutes on what is already a 20min Python build on CI, per version.

We may not need to actually build boost completely, but AFAIK `boost` headers are not linkable without the `bootstrap` and `b2` steps [here](https://github.com/boostorg/wiki/wiki/Getting-Started%3A-Overview#installing-boost) [source](https://stackoverflow.com/questions/25158084/header-files-missing-in-boost-build).

2021-03-17 02:23 UTC, texodus commented
Thanks for the PR!

2021-03-17 02:23 UTC, merged