Fix `@finos/perspective-jupyterlab` to work with WebAssembly/Webpack5
finos/perspective pull request #1377
Opened 2021-04-11 19:57 UTC by texodus

This was a nightmare and I don't want to talk about it.

2021-04-11 19:57 UTC, timkpaine commented
hahahahaha

2021-04-11 19:58 UTC, timkpaine commented
I swear I tried my best in https://github.com/finos/perspective/pull/1355

2021-04-12 16:41 UTC, sc1f requested changes

2021-04-12 16:41 UTC, sc1f commented on packages/perspective-jupyterlab/src/ts/renderer.ts
> +                this._psp.viewer.load(perspective.worker().table(data));
This will create a new WebWorker for each widget - the worker should be a property on the DocumentWidget.

2021-04-12 16:41 UTC, sc1f commented on rust/perspective-vieux/package.json
> +        "build:wasm": "wasm-pack build --target web",
We should explain this in the docs - end-users who import Perspective into their own Webpack builds will need to add the `arraybuffer-loader` in order to correctly load perspective.

2021-04-12 20:38 UTC, sc1f approved these changes
Looks good!

2021-04-12 21:19 UTC, merged