Remove parallel for from data table to fix computed column threading issue in #1831
finos/perspective pull request #1835
Opened 2022-06-04 22:19 UTC by timkpaine

2022-06-04 22:19 UTC, timkpaine commented on cpp/perspective/src/include/perspective/gnode.h
> +#ifdef PSP_ENABLE_PYTHON
this is unrelated but should be enabled conditional on PYTHON, not PARALLEL_FOR

2022-06-04 22:20 UTC, timkpaine commented
@texodus might need your help benchmarking this, if it causes a substantial degradation in performance I can try to break this loop apart to reenable some part in parallel

2022-06-06 03:23 UTC, texodus requested changes
It's not clear to my why this change would impact the test provided, so on a hunch I forked just this test to a new branch and it [passes just the same on all Linux builds](https://dev.azure.com/finosfoundation/perspective/_build/results?buildId=4456&view=logs&j=9c1f2f8e-4d43-59a0-c5f5-4a00727b21e2&t=19e3a096-6506-57cc-343b-951c3932e971&l=1558).  What am I missing?

2022-06-06 03:30 UTC, timkpaine commented
This test fails on my Linux machine, validated on 2 other Linux machines

2022-06-06 03:33 UTC, timkpaine commented
See #1835 for more details

2022-06-06 03:34 UTC, timkpaine commented
My guess would be either azure or the manylinux images themselves don't trigger the test case to fail.

2022-06-12 12:25 UTC, timkpaine commented
Some additional testing suggests this might've been fixed already via the arrow upgrade https://github.com/finos/perspective/pull/1816

2022-06-12 13:09 UTC, closed without merging

2022-06-12 19:25 UTC, texodus commented
So thanks to the accompanying test (which I _do_ want to merge), I can confirm that this issue was resolved by #1793, and is unrelated to Arrow/threading.