1237: Add support for StringDtype
finos/perspective pull request #2319
Opened 2023-07-30 11:04 UTC by MaDufie

#1237 Add support for StringDtype (available in Pandas >=1.0)

AFTER
![image](https://github.com/finos/perspective/assets/128140702/56368551-1249-4f67-9841-0748b519c824)

2023-07-31 00:30 UTC, timkpaine requested changes

2023-07-31 00:30 UTC, timkpaine commented on python/perspective/perspective/table/table.py
> +                        data = data.astype("str")
this converts the entire dataframe to “str” if any of the columns are a string

2023-07-31 00:31 UTC, timkpaine commented
You should try to implement this the same way as done here: https://github.com/finos/perspective/blob/37e3df35f0b6cc935137f669854b88b12641d3b4/python/perspective/perspective/core/data/pd.py#L75

2023-08-03 13:46 UTC, MaDufie commented
> You should try to implement this the same way as done here:
> 
> https://github.com/finos/perspective/blob/37e3df35f0b6cc935137f669854b88b12641d3b4/python/perspective/perspective/core/data/pd.py#L75
> 
> And please use the same PR as you make changes, rather than opening a new one.

@timkpaine I have implemented the changes. Kindly let me if there are any more changes after you review them. Thank you.

2023-08-07 20:31 UTC, timkpaine commented
It should be in the file linked, near the line linked.

2023-08-08 17:35 UTC, timkpaine requested changes

2023-08-08 17:35 UTC, timkpaine commented on python/perspective/perspective/table/table.py
> +import pandas as pd
Remove unneeded import
```suggestion

```

2023-08-13 20:29 UTC, timkpaine commented
@texodus this lgtm, I know we're looking to replace all of pandas / numpy with native arrow in/out so I leave up to you whether or not you want to merge.

2023-08-13 20:30 UTC, timkpaine commented on python/perspective/perspective/core/data/pd.py
> +    if isinstance(data, pd.DataFrame) and hasattr(pd, "CategoricalDtype"):
is this `hasattr` necessary?

2023-08-13 20:30 UTC, timkpaine commented on python/perspective/perspective/core/data/pd.py
> +            if isinstance(v, pd.StringDtype):
I think maybe this was meant to be used in the `hasattr`, `hasattr(pd, "StringDType")` since `StringDType` is the new type

2023-11-09 05:58 UTC, texodus approved these changes
Thanks for the PR @MaDufie! Looks good!

We should really be taking advantage of the internal dictionary for Categories, but we don't really provide any fast path loading for DataFrame yet and likely won't as we move to Arrow.

2023-11-09 05:58 UTC, merged