datagrid: add feature flag to render table in shadow DOM
finos/perspective pull request #2482
Opened 2023-12-29 21:23 UTC by tomjakubowski

When enabled, this prevents global table styles from affecting datagrid.

2024-01-01 19:17 UTC, texodus requested changes
Thanks for the PR! A couple of things need fixing:

1. I'm ok with the configuration flag being a global static on the `perspective-viewer-datagrid` element, because there is no global settings feature yet, but one is obviously needed. However, let's please rename this to `enableShadowDOM`.
2. `enableShadowDOM` should be `true` by default, e.g. we should default use the Shadow DOM. It looks like the examples work in this mode with this PR (👍 ), so no changes needed there. It is ok if the tests remain as Light DOM tests because they do some DOM surgery to check table elements, but ...
3. There needs to be at least a few tests added that test Shadow DOM mode specifically. If it's doable, I'd really like to see _all_ the tests run in parameterized in both modes, but this may be a lot of work (?)
4. The tests are currently failing regardless (looks like `perspective-jupyterlab`).
5. Let's remove the `examples/blocks` code which parses the URL.

2024-01-03 01:19 UTC, tomjakubowski commented on packages/perspective-viewer-datagrid/src/js/custom_elements/datagrid.js
> +        });
Yeah, it's also what's breaking the snapshot tests (only on Linux, though!). I think :host-context should work, I will try that

2024-01-03 01:20 UTC, tomjakubowski commented on packages/perspective-viewer-datagrid/src/js/custom_elements/datagrid.js
> +export const HTMLPerspectiveViewerDatagridPluginElement = class extends HTMLElement {
not a clue where that came from, weird! Maybe an accidental auto-fix in VSCode or something

2024-01-03 01:20 UTC, tomjakubowski commented on examples/blocks/src/magic/index.js
> +};
yeah leftover from debugging

2024-01-03 01:25 UTC, tomjakubowski commented
> I'm ok with the configuration flag being a global static on the perspective-viewer-datagrid element, because there is no global settings feature yet, but one is obviously needed. However, let's please rename this to enableShadowDOM.

Another API I was thinking about was sticking it as an attribute/flag on `<perspective-viewer>`, like `<perspective-viewer shadow />`. A problem is I imagine it would be disastrous to update a particular element to use/not use shadow DOM at runtime, i.e. to toggle usage of shadow DOM in response to changes to that attribute.

> There needs to be at least a few tests added that test Shadow DOM mode specifically. If it's doable, I'd really like to see all the tests run in parameterized in both modes, but this may be a lot of work (?)

I'll try this, it's a good idea to rerun the same tests with shadow DOM enabled/disabled. And I'll think about a test or two just for shadow DOM

2024-01-17 01:59 UTC, tomjakubowski commented
All the checks are passing now, re-review?

2024-01-17 02:00 UTC, tomjakubowski commented on packages/perspective-viewer-datagrid/src/js/custom_elements/datagrid.js
> +        });
updated

2024-01-17 02:01 UTC, tomjakubowski commented on tools/perspective-test/results.tar.gz
curious if you have any recommendations for quickly diffing these tarballs?

2024-01-18 20:36 UTC, texodus commented on tools/perspective-test/results.tar.gz
Not sure what you mean. In theory, if the snapshots don't change, the tarball should be identical. We've added a few [flags to the gzip process](https://github.com/finos/perspective/blob/master/tools/perspective-test/src/js/global_teardown.ts#L35) to force this to be the case regardless of things like file creation time.

I have noticed that this is not always the case, but I don't know why yet, nor have I even validated that this is an issue with the _tarball_ or the actual files.

2024-01-22 01:39 UTC, texodus approved these changes
Thanks for the PR! Looks good!

2024-01-22 01:39 UTC, merged

2024-05-07 17:06 UTC, jakehadar commented
> > I'm ok with the configuration flag being a global static on the perspective-viewer-datagrid element, because there is no global settings feature yet, but one is obviously needed. However, let's please rename this to enableShadowDOM.
> 
> Another API I was thinking about was sticking it as an attribute/flag on `<perspective-viewer>`, like `<perspective-viewer shadow />`. A problem is I imagine it would be disastrous to update a particular element to use/not use shadow DOM at runtime, i.e. to toggle usage of shadow DOM in response to changes to that attribute.
> 
> > There needs to be at least a few tests added that test Shadow DOM mode specifically. If it's doable, I'd really like to see all the tests run in parameterized in both modes, but this may be a lot of work (?)
> 
> I'll try this, it's a good idea to rerun the same tests with shadow DOM enabled/disabled. And I'll think about a test or two just for shadow DOM

Hi, was this attribute flag ever exposed publicly? Looks like it is a static/private attribute set at runtime based on browser capaibility  https://github.com/finos/perspective/blame/84605851230c3dd1cc58652b47babd04cc9fcc31/packages/perspective-viewer-datagrid/src/js/custom_elements/datagrid.js#L141 
This introduces inconsistencies between browsers and i believe the shadow rendering policy should be something the consumer can opt-out of

2024-05-08 18:01 UTC, tomjakubowski commented
@jakehadar The inferred setting is a default. You can override it by using [`customElements.whenDefined()`](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/whenDefined) to access the custom element constructor when it is added to the registry, and then set the `renderTarget` property on it to whichever you prefer.

```
customElements.whenDefined("perspective-viewer-datagrid").then((datagrid) => {
  console.log("setting datagrid render target");
  datagrid.renderTarget = "light";
});
```

`datagrid.renderTarget` is currently an undocumented API, but I don't anticipate it will change in the near term.

2024-05-09 12:21 UTC, jakehadar commented
Awesome, this is exactly what I need. Thank you for the quick response!Sent from my iPhoneOn May 8, 2024, at 14:01, Tom Jakubowski ***@***.***> wrote:﻿
@jakehadar The inferred setting is a default. You can override it by using customElements.whenDefined() to access the custom element constructor when it is added to the registry, and then set the renderTarget property on it to whichever you prefer.
customElements.whenDefined("perspective-viewer-datagrid").then((datagrid) => {
  console.log("setting datagrid render target");
  datagrid.renderTarget = "light";
});

datagrid.renderTarget is currently an undocumented API, but I don't anticipate it will change in the near term.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>