Show appropriate date when date is part of grouped data on chart.
finos/perspective pull request #2857
Opened 2024-11-19 10:42 UTC by onesimus-wiafe

This PR addresses issue #2566. When the data is grouped and a date is part of the grouped data, the date values are then represented in epoch format. I couldn't figure out the exact source of the problem, and this solution addresses the problem. I included a function in the filter.ts file since all the plugins affected by this issue import the functions in filter.ts. I refine the date type values before the functions in filter.ts run. The tests included confirm this solution too.

### Pull Request Checklist

-   [ x ] Description which clearly states what problems the PR solves.
-   [ x ] Description contains a link to the Github Issue, and any relevent
        Discussions, this PR applies to.
-   [ x ] Include new tests that fail without this PR but passes with it.
-   [ ] Include any relevent Documentation changes related to this change.
-   [ x ] Verify all commits have been _signed_ in accordance with the DCO policy.
-   [ ] Reviewed PR commit history to remove unnecessary changes.
-   [ ] Make sure your PR passes _build_, _test_ and _lint_ steps _completely_.

2024-11-25 11:00 UTC, aszenz commented on packages/perspective-viewer-d3fc/src/ts/legend/filter.ts
> +    let dataToRefine = data !== undefined ? data : settings.data;
```suggestion
    let dataToRefine = data ?? settings.data;
```

2025-02-10 03:47 UTC, texodus requested changes
Thanks for the PR!

I suspect some parts of this PR are AI generated. We do not yet have an official project policy on this, but I'm not eager to review such code. If you're going to use these tools, please _rigorously_ check for relevance, brevity and sanity before submitting - technically _correct_ code is not enough. If this is not AI generated code - please do this anyway.

Regardless of the tooling, I would like some cleanup of this code before we merge it (see review comments).

2025-02-10 03:47 UTC, texodus commented on packages/perspective-viewer-d3fc/src/ts/legend/filter.ts
> +    data: any[] | undefined = undefined
This is a strange API for this function - especially because you only call it with `settings.data` as the 2nd argument.

2025-02-10 03:47 UTC, texodus commented on packages/perspective-viewer-d3fc/test/js/axisLabel.spec.ts
> +        await page.waitForSelector("perspective-viewer");
This doesn't do anything if you've already clicked the plugin button - you are awaiting a selector you already interacted with on the previous line.

2025-02-10 03:47 UTC, texodus commented on packages/perspective-viewer-d3fc/test/js/axisLabel.spec.ts
> +            if (!plugin_element) return [];
These early returns only fail because the `confirmDateData` function fails for empty arrays - why not just throw/return an error here so we get a real message for the test failure?

2025-02-10 03:47 UTC, texodus commented on packages/perspective-viewer-d3fc/test/js/axisLabel.spec.ts
> +            );
Why does this select `div d3fc-group d3fc-svg.y-axis.left-axis svg` only to drop it on line 85? I think this was intended to be `div d3fc-group d3fc-svg.y-axis.left-axis svg g.group` (without a comma), but because you only take the "last" group the extra selects does not affect the test outcome. It does make this code hard to read though. You could also just combine this entire section into the selector `div d3fc-group d3fc-svg.y-axis.left-axis svg g.group:last-child g.tick text`.

2025-02-10 03:47 UTC, texodus commented on packages/perspective-viewer-d3fc/src/ts/legend/filter.ts
> +                ? (value: any) => new Date(value).toLocaleDateString()
We should really use the formatting logic from `perspective-viewer-datagrid` here ... but in the interim, this only works for `date` Perspective types. `datetime` types should use `toLocaleString()` for now please.

2025-02-10 10:14 UTC, onesimus-wiafe commented on packages/perspective-viewer-d3fc/test/js/axisLabel.spec.ts
> +    const index = Math.floor(Math.random() * len);
I thought it would be wasteful to check through the entire array and if the first, last, and a random index of the array contain dates, it was highly likely that the array contains only date types. `Date.parse()` confirms they are dates but not the way to verify that they were not in epoch form. For 58, I realized that only epoch formats would be dates after completing the regex and it felt unnecessary to continue with the steps I outlined. Even if it was not 10 or 13 digits, it was still not the form required. I could add the remaining conditions though. @texodus

2025-02-10 10:41 UTC, onesimus-wiafe commented on packages/perspective-viewer-d3fc/src/ts/legend/filter.ts
> +    data: any[] | undefined = undefined
I first wrote the implementation in the `filterData` function and when I realized `filterDataByGroup` would also need it, I made it a function on its own. Because of how filterData was defined, I decided to define the new function similarly so that I don't lose data, but I just noticed I still used `settings.data` in the new function which makes the whole endeavor redundant.

2025-02-11 12:00 UTC, onesimus-wiafe commented on packages/perspective-viewer-d3fc/test/js/axisLabel.spec.ts
> +        await page.waitForSelector("perspective-viewer");
`await page.waitForSelector("perspective-viewer")` was added to obtain the reloaded page. When a test is run without this call, the data array returned to be verified is empty.

2025-02-11 12:01 UTC, onesimus-wiafe commented on packages/perspective-viewer-d3fc/test/js/axisLabel.spec.ts
> +    const index = Math.floor(Math.random() * len);
I will split the current solution into 2, one that confirms that the entire array is of date values, and another that confirms that they are not in epoch form.

2025-02-27 03:49 UTC, texodus approved these changes
Looks good!

2025-02-27 03:50 UTC, merged